package Domain.Store.StoreData;

import java.util.ArrayList;
import java.util.List;

public enum Permissions {
    // Permissions examples for now. Will be updated later.
    ADD_PRODUCT,
    REMOVE_PRODUCT,
    EDIT_PRODUCT,
    ADD_DISCOUNT,
    REMOVE_DISCOUNT,
    EDIT_DISCOUNT,
    ADD_MANAGER,
    REMOVE_MANAGER,
    ADD_OWNER,
    REMOVE_OWNER,
    ADD_PERMISSIONS,
    REMOVE_PERMISSIONS,
    VIEW_PURCHASE_HISTORY,
    VIEW_MESSAGES,
    REPLY_MESSAGES,
    VIEW_STORE_HISTORY,
    VIEW_STORE_MANAGERS,
    VIEW_STORE_OWNERS,
    VIEW_STORE_DISCOUNTS,
    VIEW_STORE_PRODUCTS,
    VIEW_STORE_PURCHASES,
    VIEW_STORE_MESSAGES,
    VIEW_STORE_HISTORY_BY_PRODUCT,
    VIEW_STORE_HISTORY_BY_STORE,
    VIEW_STORE_HISTORY_BY_USER,
    VIEW_STORE_HISTORY_BY_MANAGER,
    VIEW_STORE_HISTORY_BY_OWNER,
    VIEW_STORE_HISTORY_BY_DATE,
    VIEW_STORE_HISTORY_BY_PRICE,
    VIEW_STORE_HISTORY_BY_RATING,
    VIEW_STORE_HISTORY_BY_PRODUCT_CATEGORY,
    VIEW_STORE_HISTORY_BY_PRODUCT_NAME,
    VIEW_STORE_HISTORY_BY_PRODUCT_RATING,
    VIEW_STORE_HISTORY_BY_PRODUCT_PRICE,
    VIEW_STORE_HISTORY_BY_PRODUCT_AMOUNT,
    VIEW_STORE_HISTORY_BY_PRODUCT_PURCHASES,
    VIEW_STORE_HISTORY_BY_PRODUCT_DISCOUNTS,
    VIEW_STORE_HISTORY_BY_PRODUCT_STORE,
    VIEW_STORE_HISTORY_BY_PRODUCT_OWNER,
    VIEW_STORE_HISTORY_BY_PRODUCT_MANAGER,
    VIEW_STORE_HISTORY_BY_PRODUCT_DATE,
    VIEW_STORE_HISTORY_BY_PRODUCT_MESSAGE,
    VIEW_STORE_HISTORY_BY_PRODUCT_PERMISSIONS,
    VIEW_STORE_HISTORY_BY_PRODUCT_PRODUCTS,
    VIEW_STORE_HISTORY_BY_PRODUCT_OWNERS,
    VIEW_STORE_HISTORY_BY_PRODUCT_MANAGERS,
    VIEW_STORE_HISTORY_BY_PRODUCT_MESSAGES,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_STORE,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_USER,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_MANAGER,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_OWNER,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_DATE,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRICE,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_RATING,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_CATEGORY,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_NAME,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_RATING,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_PRICE,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_AMOUNT,
    VIEW_STORE_HISTORY_BY_PRODUCT_HISTORY_BY_PRODUCT_PURCHASES;

    public static List<Permissions> convertStringList(List<String> permissions) {
        List<Permissions> permissionList = new ArrayList<>();
        for (String permission : permissions) {
            permissionList.add(Permissions.valueOf(permission));
        }
        return permissionList;
    }

    public static List<String> convertPermissionList(List<Permissions> permissions) {
        List<String> permissionList = new ArrayList<>();
        for (Permissions permission : permissions) {
            permissionList.add(permission.toString());
        }
        return permissionList;
    }

    public static boolean exists(String permission) {
        try {
            Permissions.valueOf(permission);
        } catch (IllegalArgumentException e) {
            return false;
        }
        return true;
    }
}
