name: Move Issues to In Progress

on:
  create:
    branches:
      - '**'

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v2

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

    - name: Extract issue number from branch name
      id: extract-issue
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oE '[0-9]+')
        echo "::set-output name=issue_number::$ISSUE_NUMBER"
      shell: bash

    - name: Move issue to In Progress
      if: steps.extract-issue.outputs.issue_number
      run: |
        ISSUE_NUMBER=${{ steps.extract-issue.outputs.issue_number }}
        PROJECT_COLUMN_ID=$(gh project column list --project "Version 1 - Repair" --json name,id | jq -r '.[] | select(.name=="In Progress") | .id')
        gh project card create --column $PROJECT_COLUMN_ID --content "Issue #$ISSUE_NUMBER"
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
